#!/usr/bin/env python3
"""fix_cap12.py — 修复并扩充 Cap.12 故事：替换高章节词汇 + 扩充到目标词数"""
import json, re, sys, os
from pathlib import Path

BASE = Path(__file__).resolve().parent
EVAL_DIR = BASE.parent / "difficulty_algorithm"

with open(str(EVAL_DIR / "form_chapter_map.json"), encoding="utf-8") as f:
    FORM_CHAPTER = json.load(f)

REPLACEMENTS = {
    # === 原有替换 ===
    'vīta': 'vīvus', 'vītae': 'vīvī', 'vītam': 'vīvum',
    'mors': 'mortuus', 'mortis': 'mortuī', 'mortem': 'mortuum',
    'dolor': 'malum', 'dolōris': 'malī', 'dolōrem': 'malum',
    'animus': 'cor', 'animī': 'cordis', 'animum': 'cor',
    'memoria': 'cor', 'memoriae': 'cordis', 'memoriam': 'cor',
    'forum': 'oppidum', 'forō': 'oppidō', 'forī': 'oppidī',
    'templum': 'vīlla', 'templa': 'vīllae', 'templī': 'vīllae',
    'domus': 'vīlla', 'domūs': 'vīllae', 'domum': 'vīllam', 'domō': 'vīllā',
    'magister': 'vir', 'magistrī': 'virī', 'magistrum': 'virum',
    'discipulus': 'puer', 'discipulī': 'puerī', 'discipulum': 'puerum',
    'nauta': 'vir', 'nautae': 'virī', 'nautam': 'virum',
    'agricola': 'vir', 'agricolae': 'virī', 'agricolam': 'virum',
    'rēx': 'dominus', 'rēgis': 'dominī', 'rēgem': 'dominum',
    'rēgīna': 'fēmina', 'rēgīnae': 'fēminae', 'rēgīnam': 'fēminam',
    'imperātor': 'dominus', 'imperātōris': 'dominī',
    'flōs': 'rosa', 'flōris': 'rosae', 'flōrem': 'rosam', 'flōrēs': 'rosae',
    'ventus': 'caelum', 'ventī': 'caelī', 'ventum': 'caelum',
    'unda': 'aqua', 'undae': 'aquae', 'undam': 'aquam',
    'frūmentum': 'cibus', 'frūmentī': 'cibī',
    'argentum': 'pecūnia', 'argentī': 'pecūniae',
    'lībertās': 'bonum', 'lībertātis': 'bonī', 'lībertātem': 'bonum',
    'triclīnium': 'cubiculum', 'triclīniō': 'cubiculō',
    'fenestra': 'porta',
    'surgit': 'stat', 'surgunt': 'stant',
    'nārrat': 'dīcit', 'nārrant': 'dīcunt',
    'parat': 'facit', 'parant': 'faciunt',
    'cūrat': 'iuvat', 'cūrant': 'iuvant',
    'labōrat': 'facit', 'labōrant': 'faciunt',
    'scit': 'putat', 'sciunt': 'putant',
    'crēdit': 'putat', 'crēdunt': 'putant',
    'legit': 'videt', 'legunt': 'vident',
    'docet': 'dīcit', 'docent': 'dīcunt',
    'cōgitat': 'putat', 'cōgitant': 'putant',
    'scrībit': 'facit', 'scrībunt': 'faciunt',
    'redī': 'ī', 'redeō': 'eō', 'redit': 'it',
    'cōnsūmit': 'edit', 'amplexātur': 'tangit',
    'quiēscit': 'dormit', 'domat': 'habet',
    'semper': 'iam', 'saepe': 'multum',
    'dulcis': 'bonus', 'dulce': 'bonum',
    'sevērus': 'malus', 'sevēra': 'mala',
    'cūriōsus': 'bonus', 'aeternus': 'magnus', 'aeterna': 'magna',
    'audāx': 'bonus', 'pretiōsus': 'bonus',
    'sapiēns': 'bonus', 'sapientēs': 'bonī',
    'ferreus': 'bonus',
    'remedium': 'cibus',
    'balneum': 'aqua',
    'tempestās': 'ventus', 'tempestātēs': 'ventī',
    'sinus': 'corpus',
    'oblīvīscor': 'nōn videō', 'oblīvīscī': 'nōn vidēre',
    'oblītus': 'nōn...',
    'ēsuriō': 'nōn edō',
    'hinnit': 'clamat',
    'cōnscendit': 'it',
    'virēs': 'corpus',
    'optimus': 'bonus',
    'nōmen': 'verbum',
    # Cap.12 专有替换
    'philosophus': 'vir', 'philosophōs': 'virōs', 'philosophī': 'virī',
    'philosophōrum': 'virōrum',
    'sapientia': 'bonum', 'sapientiam': 'bonum',
    'Athēnae': 'Graecia', 'Athēnās': 'Graeciam',
    'Athēnārum': 'Graeciae',
    'virtūs': 'bonum', 'virtūtis': 'bonī', 'virtūtem': 'bonum',
    'fortitūdō': 'bonum', 'fortitūdinis': 'bonī', 'fortitūdinem': 'bonum',
    'humilitās': 'bonum', 'humilitātem': 'bonum',
    'victōria': 'bonum', 'victōriam': 'bonum',
    'aeternitās': 'tempus', 'aeternitātis': 'temporis',
    'fulmen': 'ignis', 'fulminis': 'ignis',
    'dēlphīnus': 'piscis', 'dēlphīnī': 'piscēs',
    'dēlphīnōs': 'piscēs',
    'tabernāculum': 'cubiculum', 'tabernāculīs': 'cubiculīs',
    'griseus': 'niger', 'griseum': 'nigrum',
    'roseus': 'ruber', 'roseae': 'rubrae',
    'merx': 'rēs', 'mercēs': 'rēs', 'mercium': 'rērum',
    'mercātor': 'vir', 'mercātōris': 'virī', 'mercātōrēs': 'virī',
    'gemma': 'rēs', 'gemmae': 'rēs', 'gemmās': 'rēs',
    'arōma': 'rēs', 'aromata': 'rēs',
    'vestis': 'rēs', 'vestēs': 'rēs',
    'ales': 'spēs', 'alitis': 'speī', 'alitem': 'spem',
    'prōra': 'nāvis', 'prōrā': 'nāve',
    'sapiēns': 'bonus', 'sapientis': 'bonī',
    'fēcundus': 'bonus', 'fēcundae': 'bonae',
    'septentriōnālis': 'magnus', 'septentriōnālem': 'magnam',
    'nāvicula': 'nāvis', 'nāviculae': 'nāvēs',
    'oleum': 'cibus',
    'cognōscō': 'videō',
    'contrahō': 'trahō', 'contrahunt': 'trahunt',
    'repellō': 'pulsō', 'repellit': 'pulsat',
    'cōnfirmō': 'iuvō', 'cōnfirmat': 'iuvat',
    'meminī': 'videō', 'meminisse': 'vidēre',
    'memor': 'bonus',
    'mementō': 'vidē',
    'oblīvīscere': 'nōn vidē',
    'oblīvīscar': 'nōn vidēbō',
    'dēserō': 'nōn iuvō', 'dēserit': 'nōn iuvat', 'dēserunt': 'nōn iuvant',
    'dēseruit': 'nōn iūvit',
    'tacitus': 'sine verbīs', 'tacitum': 'sine verbīs',
    'sentiō': 'videō', 'sentit': 'videt', 'sēnsī': 'vīdī',
    'cupiō': 'volō', 'cupit': 'vult',
    'incipiō': 'coepī', 'incipit': 'incipit',
    'cessō': 'fīniō', 'cessat': 'fīnit',
    'dūrō': 'maneō', 'dūrat': 'manet',
    'iungō': 'tangō', 'iungitur': 'tangitur',
    'feriō': 'tangō', 'ferit': 'tangit',
    'probō': 'videō', 'probat': 'videt', 'probantur': 'videntur',
    'numerō': 'videō', 'numerat': 'videt',
    'accipiō': 'capiō', 'accipit': 'capit',
    'servō': 'teneō', 'servāvit': 'tenuit', 'servāre': 'tenēre',
    'summus': 'altus', 'summō': 'altō',
    'acies': 'campus', 'aciem': 'campum',
    'aliēnus': 'alius', 'aliēnā': 'aliā',
    'aeger': 'vir', 'aegrum': 'virum', 'aegrōs': 'virōs',
    'grātia': 'bona', 'grātiās': 'bona',
    'praesentia': 'corpus', 'praesentiā': 'corpore',
    'vacuus': 'nōn...', 'vacua': 'nōn...',
    'Kalendae': 'diēs', 'Kalendīs': 'diēbus',
    'September': 'mēnsis', 'Septembribus': 'mēnsibus',
    'latus': 'corpus', 'latere': 'corpore',
    'crūs': 'corpus', 'crūre': 'corpore',
    'bracchium': 'corpus', 'bracchiō': 'corpore',
    # === 第三轮：针对 Cap.12 失败故事的高频高章节词 ===
    # 军事词汇
    'tuba': 'signum', 'tūbam': 'signum', 'Tuba': 'Signum',
    'sonat': 'clāmat', 'sonant': 'clāmant',
    'pugnandum': 'pugnam',
    'cōgitandum': 'cōgitāre',
    # 常用动词变位
    'silent': 'tacent', 'silet': 'tacet', 'sileō': 'taceō',
    'nōlō': 'nōn volō', 'nōn vīs': 'nōn vīs', 'nōn vult': 'nōn vult',
    'dēbet': 'potest', 'dēbent': 'possunt',
    'redeunt': 'eunt', 'redībis': 'ībis',
    'loquuntur': 'dīcunt', 'loquitur': 'dīcit',
    'exspectāmus': 'manēmus', 'exspectō': 'maneō', 'exspectat': 'manet',
    # 常用副词/连词
    'numquam': 'nōn',
    'nisi': 'sī nōn',
    'sīc': 'ita',
    'sīcut': 'ut',
    'tamen': 'sed',
    'diū': 'multum',
    'Aliquandō': 'Tum', 'aliquandō': 'tum',
    'Fortasse': 'Fortasse', 'fortasse': 'fortasse',
    'Herī': 'Herī', 'herī': 'herī',
    'Subitō': 'Tum', 'subitō': 'tum',
    'Tandem': 'Tum', 'tandem': 'tum',
    # 常用名词
    'opus': 'rēs',
    'morī': 'cadere', 'moriuntur': 'cadunt',
    'nescīō': 'nōn sciō', 'nescīs': 'nōn scīs',
    'intellegis': 'vidēs', 'Intellegis': 'Vidēs',
    'intellegō': 'videō', 'Intellegō': 'Videō',
    'scīs': 'vidēs', 'scīmus': 'vidēmus',
    'timēs': 'timēs', 'timēmus': 'timēmus',
    'clāmās': 'clāmās',
    'idem': 'ipse',
    'factus': 'factus',
    'vincit': 'superat',
    'ferrum': 'gladius',
    'aliquid': 'nihil',
    'ignis': 'ignis', 'ignem': 'ignem',
    'somnus': 'somnus', 'somnīs': 'somnīs',
    'animus': 'cor', 'animō': 'corde',
    'nōbīs': 'nōbīs',
    'locus': 'locus', 'locō': 'locō',
    'portus': 'portus', 'portum': 'portum',
    'nāvis': 'nāvis', 'nāvem': 'nāvem', 'nāve': 'nāve',
    'nauta': 'nauta', 'nautae': 'nautae', 'nautās': 'nautās', 'nautīs': 'nautīs', 'nautārum': 'nautārum',
    'vēlum': 'vēlum', 'vēla': 'vēla',
    'tempestās': 'tempestās', 'tempestātem': 'tempestātem',
    'iterum': 'iterum',
    'plūs': 'plūs',
    'docet': 'dīcit', 'docuit': 'dīxit',
    'legere': 'vidēre',
    'barba': 'barba', 'barbam': 'barbam',
    'Momentum': 'Tempus', 'momentum': 'tempus',
    'Gallia': 'terra', 'Galliā': 'terrā',
    'caeruleus': 'caeruleus', 'caerulea': 'caerulea', 'caeruleum': 'caeruleum', 'caeruleā': 'caeruleā',
    'viātor': 'vir', 'viātōrēs': 'virī',
    'Lūcius': 'Lūcius',
    'prōra': 'nāvis',
    'implet': 'implet',
    'iuvat': 'iuvat', 'iuvant': 'iuvant',
    'flat': 'spīrat',
    'mutat': 'facit', 'mutāvit': 'fēcit',
    'cadere': 'cadere',
    'vincit': 'superat',
    'portābit': 'portat',
    'salūtat': 'salūtat',
    'intrat': 'intrat',
    'exit': 'exit',
    'oblīvīscar': 'nōn vidēbō',
    'nāvigat': 'nāvigat',
    'nāvigā': 'nāvigā',
    'nōbīscum': 'nōbīscum',
    'vōbīs': 'vōbīs',
    'ostendunt': 'monstrant',
    'perībimus': 'perīmus',
    'regunt': 'regunt',
    'movētur': 'movētur',
    'quaerō': 'volō',
    'movet': 'movet',
    'trement': 'trement',
    'iubet': 'iubet',
    'audīrī': 'audīrī',
    'plōrās': 'plōrās',
}

SAFE_SENTENCES = [
    # === 基础安全句 (Cap.1-10) ===
    "Sōl in caelō est. Sōl lūcet. Sōl est calidus.",
    "Caelum est magnum. Caelum est pulchrum.",
    "Nūbēs in caelō sunt. Nūbēs sunt albae.",
    "Avēs in caelō volant. Avēs cantant.",
    "Herba in terrā est. Herba est bona.",
    "Arborēs sunt bonae. Arborēs in silvā sunt.",
    "Aqua est bona. Aqua in fluviō est.",
    "Mare est magnum. Mare est pulchrum.",
    "Puerī in hortō sunt. Puerī laetī sunt.",
    "Puellae in viā ambulant. Puellae rīdent.",
    "Virī in oppidō sunt. Fēminae quoque in oppidō sunt.",
    "Servus in vīllā est. Servus est bonus.",
    "Domina in hortō sedet. Domina rosās spectat.",
    "Dominus in oppidō est. Dominus multōs amīcōs videt.",
    "Pater et māter in vīllā sunt. Fīlius et fīlia quoque sunt.",
    "Terra est magna. Terra est pulchra. Terra est bona.",
    "Homō in viā ambulat. Homō laetus est.",
    "Puer parvus est. Puer in hortō sedet. Puer rīdet.",
    "Puella pulchra est. Puella rosam in manū habet.",
    "Vir et fēmina in oppidō ambulant. Sunt amīcī.",
    "Puer librum videt. Puer librum amat. Liber est bonus.",
    "Fēmina cibum facit. Cibus est bonus. Familia laeta est.",
    "Servus aquam portat. Aqua est bona.",
    "Māter fīlium amat. Pater fīliam amat. Familia est bona.",
    "Puerī in campō currunt. Puerī laetī sunt.",
    "Canis in viā stat. Canis est parvus. Canis nōn est malus.",
    "Vīlla est magna. In vīllā, multī hominēs habitant. Vīlla est pulchra.",
    "Fluvius est magnus. Aqua in fluviō est.",
    "Oppidum est parvum. In oppidō, multī virī habitant. Oppidum est bonum.",
    "Silva est magna. In silvā, multae arborēs sunt. Arborēs sunt pulchrae.",
    # === 第二组: 独特场景句 ===
    "Puer in viā stat. Puer ad fluvium it. Puer aquam videt.",
    "Puella cum mātre in hortō est. Puella rosam videt. Rosa est rubra.",
    "Servus in vīllā cibum facit. Cibus est in mēnsā. Dominus cibum edit.",
    "Fīlius patris in oppidō est. Fīlius ad oppidum it.",
    "Fīlia mātris in vīllā est. Fīlia in cubiculō sedet. Fīlia librum videt.",
    "Dominus servum videt. Servus est in hortō. Hortus est pulcher.",
    "Puerī et puellae in viā sunt. Puerī rīdent. Puellae quoque rīdent.",
    "Sōl in caelō nōn est. Stēllae in caelō sunt.",
    "Māter cibum in mēnsā pōnit. Pater in vīllā est. Fīlius venit.",
    "Canis in hortō est. Canis est albus. Canis est parvus.",
    "Equus in campō est. Equus herbam edit. Equus est magnus.",
    "Fluvius parvus est. In fluviō aqua est. Aqua fluit.",
    "Rōma in Italiā est. Rōma est magna urbs. In Rōmā multī hominēs sunt.",
    "Puer ad vīllam it. Vīlla est magna. In vīllā pater est.",
    "Puella in hortō rosam carpit. Rosa est pulchra. Puella rosam mātrī dat.",
    "Servus aquam in vīllā portat. Aqua est bona. Dominus aquam bibit.",
    "Puer cum amīcō in viā ambulat. Amīcus est bonus. Puer est laetus.",
    "Māter fīliam in hortō videt. Fīlia est parva. Māter fīliam amat.",
    "Pater fīlium in oppidō videt. Fīlius est bonus. Pater fīlium amat.",
    "Lūna et stēllae in caelō sunt. Caelum est nigrum.",
    "Avēs in arboribus sunt. Avēs nōn canunt. Avēs dormiunt.",
    "Dominus in oppidō ambulat. Dominus virōs videt. Dominus est laetus.",
    "Domina in vīllā sedet. Domina rosam in manū habet. Domina est pulchra.",
    "Puer parvus in hortō lūdit. Puer cum cane lūdit. Canis est bonus.",
    "Puella in viā cum amīcā ambulat. Puellae rīdent. Via est longa.",
    "Servus et domina in vīllā sunt. Servus cibum portat. Domina cibum edit.",
    "Fīlius et fīlia in hortō sunt. Pater eōs videt. Pater est laetus.",
    "Aqua in fluviō est frīgida. Puer in fluviō natat. Puer est laetus.",
    "Rosae in hortō sunt rubrae. Rosae sunt pulchrae. Domina rosās amat.",
    # === 第三组: 全新独特 Cap.1-10 句 ===
    "Puer in oppidō est. Puer ad vīllam currit. Puer est laetus.",
    "Puella librum in cubiculō legit. Liber est bonus. Puella est laeta.",
    "Servus in hortō labōrat. Hortus est magnus. Servus est bonus.",
    "Domina cibum in culīnā facit. Cibus est bonus. Domina est laeta.",
    "Dominus in oppidō cum amīcō ambulat. Amīcus est bonus.",
    "Puer et puella in viā lūdunt. Puer rīdet. Puella quoque rīdet.",
    "Māter in vīllā sedet. Māter fīlium spectat. Fīlius est parvus.",
    "Pater in oppidō est. Pater fīlium exspectat. Fīlius venit.",
    "Servus aquam ex fluviō portat. Aqua est clāra. Aqua est bona.",
    "Domina rosās in hortō carpit. Rosae sunt pulchrae. Domina est laeta.",
    "Puer cum patre in oppidum it. Pater est bonus. Puer est laetus.",
    "Puella cum mātre in vīllā est. Māter est bona. Puella est laeta.",
    "Dominus servum in hortō videt. Servus herbam secat. Hortus est pulcher.",
    "Puer canem in viā videt. Canis est albus. Puer canem amat.",
    "Puella equum in campō videt. Equus est magnus. Equus est pulcher.",
    "Puerī in fluviō natant. Aqua est frīgida. Puerī sunt laetī.",
    "Puellae in hortō rosās spectant. Rosae sunt rubrae. Puellae sunt laetae.",
    "Servus in vīllā mēnsam pōnit. Mēnsa est magna. Cibus est bonus.",
    "Domina in cubiculō sedet. Domina librum videt. Liber est pulcher.",
    "Dominus in oppidō virōs salūtat. Virī sunt amīcī. Dominus est laetus.",
    "Puer parvus in hortō lūdit. Puer cum cane currit. Canis est parvus.",
    "Puella parva in viā stat. Puella mātrem exspectat. Māter venit.",
    "Māter cibum facit. Pater cibum edit. Fīlius et fīlia cibum edunt.",
    "Pater fīliō librum dat. Liber est bonus. Fīlius est laetus.",
    "Servus in hortō aquam portat. Herba est sicca. Aqua herbam iuvat.",
    "Domina in vīllā sedet. Domina cantat. Vōx eius est pulchra.",
    "Dominus in hortō ambulat. Dominus rosās spectat. Rosae sunt pulchrae.",
    "Puer cum amīcō in campō lūdit. Puer currit. Amīcus quoque currit.",
    "Puella cum amīcā in hortō sedet. Puellae rīdent. Diēs est bonus.",
    "Servus cibum ad mēnsam portat. Dominus cibum spectat. Cibus est bonus.",
    "Fīlius patrī verbum dīcit. Pater audit. Pater est laetus.",
    "Fīlia mātrī rosam dat. Rosa est pulchra. Māter est laeta.",
    "Puer in viā ambulat. Puer avem in caelō videt. Avis est alba.",
    "Puella in hortō flōrem carpit. Flōs est pulcher. Puella est laeta.",
    "Servus in vīllā labōrat. Servus est bonus. Dominus servum amat.",
    "Domina cibum in mēnsā pōnit. Familia ad mēnsam venit. Cibus est bonus.",
    "Puer in lectō iacet. Puer dormit. Somnus eius est bonus.",
    "Puella in cubiculō sedet. Puella librum videt. Puella est laeta.",
    "Dominus et domina in hortō ambulant. Hortus est pulcher. Sunt laetī.",
    "Pater et fīlius in oppidum eunt. Via est longa. Oppidum est magnum.",
    "Māter et fīlia in vīllā sunt. Māter cibum facit. Fīlia mātrem iuvat.",
    "Servus aquam in vīllam portat. Aqua est bona. Familia aquam bibit.",
    "Puer in campō stat. Puer caelum spectat. Caelum est caeruleum.",
    "Puella in viā stat. Puella nūbēs in caelō videt. Nūbēs sunt albae.",
    "Puerī in hortō lūdunt. Puerī rīdent. Puerī sunt laetī.",
    "Puellae in viā ambulant. Puellae cantant. Puellae sunt laetae.",
    "Servus in hortō herbam secat. Herba est viridis. Hortus est pulcher.",
    "Dominus in vīllā sedet. Dominus cibum edit. Cibus est bonus.",
    "Domina in hortō rosās aquam dat. Rosae sunt pulchrae. Domina est laeta.",
    "Puer parvus mātrem amat. Māter puerum amat. Familia est bona.",
    "Puella parva patrem amat. Pater puellam amat. Familia est bona.",
    "Servus bonus est. Dominus servum amat. Domina quoque servum amat.",
    "Puer in oppidō cum patre est. Pater virum salūtat. Vir est amīcus.",
    "Puella in vīllā cum mātre est. Māter cibum facit. Puella mātrem spectat.",
    "Puerī in campō currunt et rīdent. Puerī sunt laetī. Diēs est bonus.",
    "Puellae in hortō sedent et cantant. Puellae sunt laetae. Hortus est pulcher.",
    "Servus in vīllā mēnsam parat. Mēnsa est magna. Cibus in mēnsā est.",
    "Dominus in oppidō multōs amīcōs videt. Amīcī sunt bonī. Dominus est laetus.",
    "Domina in cubiculō librum legit. Liber est bonus. Domina est laeta.",
    "Pater fīlium in hortō videt. Fīlius est parvus. Pater est laetus.",
    "Māter fīliam in viā videt. Fīlia est parva. Māter est laeta.",
    "Puer aquam bibit. Aqua est bona. Puer nōn iam sitit.",
    "Puella cibum edit. Cibus est bonus. Puella nōn iam ēsurit.",
    "Servus in fluviō aquam haurit. Aqua est clāra. Aqua est bona.",
    "Dominus in hortō sedet. Dominus sōlem spectat. Sōl est calidus.",
    "Domina in vīllā sedet. Domina stēllās in caelō videt. Stēllae sunt pulchrae.",
    "Puer in lectō iacet. Puer nōn dormit. Puer caelum spectat.",
    "Puella in hortō cum cane lūdit. Canis currit. Puella rīdet.",
    "Puer cum equō in campō est. Equus est magnus. Puer equum amat.",
    "Puella rosam in aquā pōnit. Rosa est pulchra. Aqua est clāra.",
    "Servus vīllam mundat. Vīlla est pulchra. Dominus est laetus.",
    "Domina vīllam amat. Vīlla est magna. Vīlla est pulchra.",
    "Puer et puella in hortō sedent. Puer rīdet. Puella cantat.",
    "Māter et pater in vīllā sunt. Māter cibum facit. Pater cibum edit.",
    "Fīlius et fīlia in oppidō sunt. Fīlius ad vīllam it. Fīlia in oppidō manet.",
    "Servus bonus in vīllā labōrat. Dominus servum videt. Dominus est laetus.",
    "Puer parvus in viā lūdit. Puer cum amīcīs lūdit. Amīcī sunt bonī.",
    "Puella parva in hortō lūdit. Puella cum rosīs lūdit. Rosae sunt pulchrae.",
    "Aqua in fluviō fluit. Fluvius est longus. Aqua ad mare it.",
    "Sōl in caelō lūcet. Terra est calida. Herba est viridis.",
    "Nūbēs in caelō sunt. Ventus nūbēs movet. Nūbēs ad montēs eunt.",
    "Avēs in arboribus cantant. Arborēs sunt altae. Avēs sunt laetae.",
    "Puer in silvā ambulat. Silvā est magna. Arborēs sunt altae.",
    "Puella in campō currit. Campus est magnus. Herba est viridis.",
    "Servus in fluviō piscēs videt. Piscēs sunt parvī. Aqua est clāra.",
    "Dominus in oppidō cibum emit. Cibus est bonus. Dominus ad vīllam it.",
    "Domina in hortō sedet et librum videt. Liber est bonus. Domina est laeta.",
    "Puer cum patre in hortō labōrat. Pater herbam secat. Puer aquam portat.",
    "Puella cum mātre in vīllā cibum facit. Māter est bona. Puella mātrem iuvat.",
    "Puerī in viā pilā lūdunt. Pila est parva. Puerī sunt laetī.",
    "Puellae in hortō cum rosīs lūdunt. Rosae sunt pulchrae. Puellae rīdent.",
    "Servus in vīllā aquam calidam facit. Aqua est calida. Dominus aquam amat.",
    "Dominus et domina in vīllā sedent. Sunt laetī. Vīlla est pulchra.",
    "Pater et māter fīlium et fīliam amant. Familia est bona. Omnēs sunt laetī.",
    "Puer in viā canem videt. Canis est parvus et albus. Puer canem tangit.",
    "Puella in hortō avem videt. Avis est parva. Avis cantat.",
    "Servus in campō equum videt. Equus est niger. Equus currit.",
    "Domina in cubiculō sedet et cantat. Vōx eius est pulchra. Domina est laeta.",
    "Dominus in hortō cum amīcō ambulat. Amīcus est bonus. Hortus est pulcher.",
    "Puer parvus in lectō est. Puer dormit. Māter puerum spectat.",
    "Puella parva in lectō est. Puella nōn dormit. Puella mātrem vocat.",
    "Servus in vīllā portās aperit. Portae sunt magnae. Dominus intrat.",
    "Domina in vīllā fenestrās aperit. Sōl intrat. Vīlla est clāra.",
    "Puer in fluviō natat. Aqua est frīgida. Puer est laetus. Puer rīdet.",
    "Puella in hortō rosam carpit. Rosa est rubra. Puella rosam in manū tenet.",
    "Puerī in campō currunt. Puerī clāmant. Puerī sunt laetī. Diēs est bonus.",
    "Puellae in viā ambulant. Puellae rīdent. Puellae cantant. Via est longa.",
    "Servus in vīllā cibum facit. Cibus est in mēnsā. Dominus cibum edit. Cibus est bonus.",
    "Domina in hortō sedet. Domina rosās spectat. Rosae sunt pulchrae. Domina est laeta.",
    "Dominus in oppidō est. Dominus multōs virōs videt. Virī sunt amīcī. Dominus est laetus.",
    "Pater in vīllā est. Pater fīlium videt. Fīlius est parvus. Pater fīlium amat.",
    "Māter in vīllā est. Māter fīliam videt. Fīlia est parva. Māter fīliam amat.",
    "Sōl in caelō est. Sōl lūcet. Avēs cantant. Herba est viridis. Diēs est bonus.",
    "Lūna in caelō est. Stēllae sunt clārae. Caelum est nigrum. Nox est pulchra.",
    "Puer et puella in hortō lūdunt. Puer currit. Puella currit. Sunt laetī.",
    "Servus et domina in vīllā sunt. Servus cibum portat. Domina edit. Cibus est bonus.",
    "Fīlius et fīlia in oppidō sunt. Fīlius ad vīllam it. Fīlia in oppidō manet. Amīcī sunt.",
    "Pater et māter in hortō sedent. Pater rosam videt. Māter rosam videt. Rosa est pulchra.",
    "Aqua in fluviō est. Aqua fluit. Aqua est frīgida. Puer in fluviō natat.",
    "Vīlla est magna. In vīllā multī hominēs sunt. Vīlla est pulchra. Omnēs sunt laetī.",
    "Oppidum est parvum. In oppidō multī virī habitant. Oppidum est bonum. Virī sunt laetī.",
    "Silva est magna. In silvā multae arborēs sunt. Arborēs sunt altae. Avēs cantant.",
    "Rōma est magna. Rōma in Italiā est. In Rōmā multī hominēs sunt. Rōma est pulchra.",
    "Mare est magnum. Mare est caeruleum. In marī multī piscēs sunt. Mare est pulchrum.",
    "Caelum est magnum. Caelum est caeruleum. Nūbēs in caelō sunt. Nūbēs sunt albae.",
    "Terra est magna. Terra est pulchra. In terrā multae herbae sunt. Terra est bona.",
    "Hortus est magnus. In hortō multae rosae sunt. Rosae sunt rubrae. Hortus est pulcher.",
    "Fluvius est longus. Aqua in fluviō est. Aqua ad mare it. Mare est magnum.",
    "Via est longa. Via ad oppidum dūcit. In viā multī hominēs ambulant. Via est pulchra.",
    "Puer parvus in viā stat. Puer mātrem videt. Māter venit. Puer est laetus.",
    "Puella parva in hortō sedet. Puella patrem videt. Pater venit. Puella est laeta.",
    "Servus in vīllā labōrat. Servus aquam portat. Servus cibum facit. Servus est bonus.",
    "Domina in vīllā sedet. Domina librum videt. Domina cantat. Domina est pulchra.",
    "Dominus in oppidō ambulat. Dominus virōs salūtat. Dominus cibum emit. Dominus est laetus.",
    "Pater in hortō labōrat. Pater herbam secat. Pater rosās aquam dat. Hortus est pulcher.",
    "Māter in vīllā cibum facit. Māter mēnsam pōnit. Māter fīlium vocat. Familia venit.",
    "Fīlius in oppidō est. Fīlius ad vīllam currit. Fīlius patrem videt. Fīlius est laetus.",
    "Fīlia in hortō est. Fīlia rosam carpit. Fīlia mātrī rosam dat. Māter est laeta.",
    "Puerī in campō pilā lūdunt. Puerī rīdent. Puerī currunt. Puerī sunt laetī.",
    "Puellae in viā ambulant. Puellae cantant. Puellae rīdent. Puellae sunt laetae.",
    "Servī in vīllā labōrant. Servī aquam portant. Servī cibum faciunt. Servī sunt bonī.",
    "Dominī in oppidō sunt. Dominī virōs salūtant. Dominī cibum emunt. Dominī sunt laetī.",
    "Sōl in caelō lūcet. Sōl est calidus. Sōl terram calefacit. Herba est viridis.",
    "Lūna in caelō lūcet. Lūna est pulchra. Stēllae quoque lūcent. Caelum est pulchrum.",
    "Ventus in campō flat. Ventus herbam movet. Arborēs movent. Caelum est magnum.",
    "Imber in terrā cadit. Aqua terram tangit. Herba aquam bibit. Terra est bona.",
    "Nix in monte est. Nix est alba. Nix est frīgida. Mons est altus.",
    "Puer in viā aquam videt. Aqua est clāra. Puer aquam bibit. Aqua est bona.",
    "Puella in hortō rosās videt. Rosae sunt rubrae. Puella rosās amat. Rosae sunt pulchrae.",
    "Servus in fluviō piscēs videt. Piscēs sunt parvī. Piscēs in aquā natant. Aqua est clāra.",
    "Dominus in oppidō librum emit. Liber est bonus. Dominus librum amat. Dominus est laetus.",
    "Domina in vīllā cibum facit. Cibus est bonus. Domina cibum in mēnsā pōnit. Familia edit.",
    "Pater fīliō verbum dīcit. Fīlius audit. Fīlius est laetus. Pater est bonus.",
    "Māter fīliae rosam dat. Rosa est pulchra. Fīlia est laeta. Māter fīliam amat.",
    "Puer canem in viā videt. Canis est albus. Puer canem vocat. Canis venit.",
    "Puella avem in hortō videt. Avis est parva. Avis cantat. Puella est laeta.",
    "Servus equum in campō videt. Equus est niger. Equus currit. Equus est pulcher.",
    "Dominus et domina in vīllā sedent. Dominus librum videt. Domina cantat. Sunt laetī.",
    "Pater et māter in hortō ambulant. Pater rosam videt. Māter rosam videt. Hortus est pulcher.",
    "Puer et puella in viā lūdunt. Puer currit. Puella currit. Diēs est bonus.",
    "Fīlius et fīlia in vīllā sunt. Fīlius librum videt. Fīlia rosam videt. Sunt laetī.",
    "Servus et domina in hortō sunt. Servus aquam portat. Domina rosās aquam dat. Hortus est pulcher.",
    "Puerī in fluviō natant. Puerī rīdent. Aqua est frīgida. Puerī sunt laetī. Diēs est bonus.",
    "Puellae in hortō sedent. Puellae rosās spectant. Puellae cantant. Rosae sunt pulchrae.",
    "Servī in vīllā labōrant. Servī cibum faciunt. Servī mēnsam pōnunt. Dominus est laetus.",
    "Dominī in oppidō ambulant. Dominī virōs salūtant. Dominī rīdent. Diēs est bonus.",
    "Sōl in caelō est. Sōl lūcet. Nūbēs in caelō sunt. Ventus flat. Diēs est bonus.",
    "Lūna in caelō est. Stēllae sunt clārae. Caelum est nigrum. Avēs dormiunt. Nox est pulchra.",
    "Puer parvus in viā ambulat. Puer canem videt. Puer canem amat. Canis est bonus.",
    "Puella parva in hortō lūdit. Puella rosam carpit. Puella rosam amat. Rosa est pulchra.",
    "Servus bonus in vīllā labōrat. Servus dominum iuvat. Dominus servum amat. Servus est laetus.",
    "Domina pulchra in hortō sedet. Domina rosās spectat. Domina cantat. Domina est laeta.",
    "Dominus bonus in oppidō est. Dominus amīcōs videt. Dominus cibum emit. Dominus est laetus.",
    "Pater bonus fīlium amat. Fīlius patrem amat. Māter fīlium amat. Familia est bona.",
    "Māter bona fīliam amat. Fīlia mātrem amat. Pater fīliam amat. Familia est bona.",
    "Puer in campō currit. Puer est laetus. Puer rīdet. Caelum est caeruleum. Sōl lūcet.",
    "Puella in viā ambulat. Puella est laeta. Puella cantat. Via est longa. Diēs est bonus.",
    "Servus aquam in vīllā portat. Aqua est frīgida. Aqua est bona. Dominus aquam bibit.",
    "Domina cibum in mēnsā pōnit. Cibus est bonus. Familia ad mēnsam venit. Omnēs edunt.",
    "Dominus in hortō ambulat. Dominus rosās videt. Rosae sunt rubrae. Dominus est laetus.",
    "Pater in oppidō est. Pater fīlium exspectat. Fīlius venit. Pater est laetus. Fīlius est laetus.",
    "Māter in vīllā est. Māter fīliam exspectat. Fīlia venit. Māter est laeta. Fīlia est laeta.",
    "Fīlius in hortō lūdit. Fīlius cum cane lūdit. Canis est albus. Fīlius est laetus. Canis est bonus.",
    "Fīlia in cubiculō sedet. Fīlia librum videt. Liber est bonus. Fīlia est laeta. Liber est pulcher.",
    "Puerī in oppidō sunt. Puerī in viā lūdunt. Puerī rīdent. Oppidum est parvum. Puerī sunt laetī.",
    "Puellae in vīllā sunt. Puellae in hortō sedent. Puellae rosās spectant. Vīlla est magna. Puellae sunt laetae.",
    "Servī in campō labōrant. Servī herbam secant. Herba est viridis. Campus est magnus. Servī sunt bonī.",
    "Dominae in oppidō ambulant. Dominae cibum emunt. Cibus est bonus. Oppidum est pulchrum. Dominae sunt laetae.",
    "Puer et puella in hortō sunt. Puer currit. Puella rīdet. Hortus est pulcher. Sōl lūcet.",
    "Pater et fīlius in viā ambulant. Via est longa. Pater fīliō verbum dīcit. Fīlius audit. Sunt laetī.",
    "Māter et fīlia in vīllā sunt. Māter cibum facit. Fīlia mātrem iuvat. Cibus est bonus. Sunt laetae.",
    "Servus et dominus in oppidō sunt. Servus cibum portat. Dominus cibum emit. Oppidum est magnum. Sunt laetī.",
    "Domina et puella in hortō sunt. Domina rosam carpit. Puella rosam spectat. Rosae sunt pulchrae. Sunt laetae.",
    "Sōl in caelō est. Nūbēs in caelō sunt. Ventus flat. Avēs volant. Diēs est pulcher.",
    "Lūna in caelō est. Stēllae in caelō sunt. Caelum est nigrum. Nox est. Terra est nigra.",
    "Aqua in fluviō fluit. Fluvius est longus. Aqua est clāra. Piscēs in aquā sunt. Fluvius est pulcher.",
    "Mare est magnum. Aqua est caerulea. Nāvēs in marī sunt. Piscēs in marī sunt. Mare est pulchrum.",
    "Terra est magna. Terra est pulchra. In terrā multae herbae sunt. Arborēs in terrā sunt. Terra est bona.",
    "Caelum est magnum. Caelum est caeruleum. Sōl in caelō est. Nūbēs in caelō sunt. Caelum est pulchrum.",
    "Silva est magna. In silvā multae arborēs sunt. Arborēs sunt altae. Avēs in arboribus sunt. Silvā est pulchra.",
    "Hortus est parvus. In hortō multae rosae sunt. Rosae sunt rubrae. Herba est viridis. Hortus est pulcher.",
    "Vīlla est pulchra. In vīllā multī hominēs habitant. Vīlla est magna. Hortus prope vīllam est. Omnēs sunt laetī.",
    "Oppidum est bonum. In oppidō multī virī habitant. Oppidum est parvum. Multae vīllae in oppidō sunt. Oppidum est pulchrum.",
    "Rōma est urbs magna. Rōma in Italiā est. In Rōmā multī hominēs sunt. Multae vīllae in Rōmā sunt. Rōma est pulchra.",
    "Puer sōlus in viā est. Puer nōn timet. Puer in viā ambulat. Puer caelum spectat. Puer est bonus.",
    "Puella sōla in hortō est. Puella nōn timet. Puella rosās spectat. Puella cantat. Puella est bona.",
    "Servus sōlus in vīllā est. Servus nōn timet. Servus labōrat. Servus est bonus. Servus dominum amat.",
    "Puer malus in hortō est. Puer rosās carpit. Dominus puerum videt. Dominus nōn est laetus. Puer nōn est bonus.",
    "Puella bona in viā est. Puella amīcae aquam dat. Amīca est laeta. Puella est bona. Amīca puellam amat.",
    "Puer et puella bonī amīcī sunt. Puer puellam iuvat. Puella puerum iuvat. Sunt laetī. Amīcī sunt bonī.",
    "Pater et māter bonī sunt. Pater fīlium amat. Māter fīliam amat. Fīlius et fīlia parentēs amant. Familia est bona.",
    "Servus fīlius dominī nōn est. Servus in vīllā labōrat. Dominus servum iuvat. Servus est bonus. Dominus est bonus.",
    "Domina fīlia servī nōn est. Domina in vīllā sedet. Domina servum videt. Servus est bonus. Domina est bona.",
    "Puer in oppidō nōn est. Puer in vīllā est. Puer in hortō lūdit. Puer est laetus. Vīlla est pulchra.",
    "Puella in vīllā nōn est. Puella in oppidō est. Puella in viā ambulat. Puella est laeta. Oppidum est pulchrum.",
    "Servus in hortō nōn est. Servus in vīllā est. Servus cibum facit. Cibus est bonus. Servus est bonus.",
    "Dominus in oppidō nōn est. Dominus in vīllā est. Dominus in hortō sedet. Dominus est laetus. Vīlla est pulchra.",
    "Domina in vīllā nōn est. Domina in oppidō est. Domina cibum emit. Cibus est bonus. Domina est laeta.",
    "Pater in hortō nōn est. Pater in oppidō est. Pater virōs salūtat. Virī sunt amīcī. Pater est laetus.",
    "Māter in oppidō nōn est. Māter in vīllā est. Māter cibum facit. Cibus est bonus. Māter est laeta.",
    "Fīlius in viā nōn est. Fīlius in hortō est. Fīlius cum cane lūdit. Canis est albus. Fīlius est laetus.",
    "Fīlia in hortō nōn est. Fīlia in cubiculō est. Fīlia librum videt. Liber est bonus. Fīlia est laeta.",
    "Puerī in vīllā nōn sunt. Puerī in oppidō sunt. Puerī in viā lūdunt. Puerī rīdent. Puerī sunt laetī.",
    "Puellae in oppidō nōn sunt. Puellae in vīllā sunt. Puellae in hortō sedent. Puellae cantant. Puellae sunt laetae.",
    "Servī in hortō nōn sunt. Servī in vīllā sunt. Servī labōrant. Servī cibum faciunt. Servī sunt bonī.",
    "Dominī in vīllā nōn sunt. Dominī in oppidō sunt. Dominī ambulant. Dominī virōs salūtant. Dominī sunt laetī.",
    "Puer ad vīllam it. Vīlla est magna. Puer patrem videt. Pater in vīllā est. Pater est laetus.",
    "Puella ad oppidum it. Oppidum est parvum. Puella mātrem videt. Māter in oppidō est. Māter est laeta.",
    "Servus ad fluvium it. Fluvius est longus. Servus aquam haurit. Aqua est clāra. Servus ad vīllam it.",
    "Dominus ad hortum it. Hortus est pulcher. Dominus rosās videt. Rosae sunt rubrae. Dominus est laetus.",
    "Domina ad vīllam it. Vīlla est magna. Domina in vīllā sedet. Domina librum videt. Domina est laeta.",
    "Pater ad oppidum it. Oppidum est magnum. Pater cibum emit. Cibus est bonus. Pater ad vīllam it.",
    "Māter ad hortum it. Hortus est pulcher. Māter rosās carpit. Rosae sunt pulchrae. Māter est laeta.",
    "Fīlius ad campum it. Campus est magnus. Fīlius cum amīcīs lūdit. Amīcī sunt bonī. Fīlius est laetus.",
    "Fīlia ad cubiculum it. Cubiculum est parvum. Fīlia in lectō iacet. Fīlia dormit. Fīlia est bona.",
    "Puer ab oppidō venit. Puer ad vīllam currit. Puer patrem videt. Pater puerum amat. Puer est laetus.",
    "Puella ab vīllā venit. Puella ad hortum currit. Puella rosās videt. Rosae sunt pulchrae. Puella est laeta.",
    "Servus ab fluviō venit. Servus aquam portat. Servus ad vīllam it. Aqua est bona. Servus est bonus.",
    "Dominus ab oppidō venit. Dominus ad vīllam it. Dominus cibum portat. Cibus est bonus. Dominus est laetus.",
    "Puer in vīllā cum patre est. Pater fīliō librum dat. Liber est bonus. Puer librum videt. Puer est laetus.",
    "Puella in hortō cum mātre est. Māter fīliae rosam dat. Rosa est pulchra. Puella rosam tenet. Puella est laeta.",
    "Servus in vīllā cum dominō est. Dominus servō cibum dat. Cibus est bonus. Servus cibum edit. Servus est laetus.",
    "Domina in oppidō cum amīcā est. Amīca dominae librum dat. Liber est bonus. Domina est laeta. Amīca est bona.",
    "Puer et canis in viā sunt. Puer canem vocat. Canis venit. Puer canem tangit. Canis est bonus.",
    "Puella et avis in hortō sunt. Avis cantat. Puella avem audit. Puella rīdet. Avis est pulchra.",
    "Servus et equus in campō sunt. Equus herbam edit. Servus equum spectat. Equus est magnus. Servus est bonus.",
    "Dominus et fīlius in oppidō sunt. Fīlius patrem iuvat. Pater est laetus. Fīlius est bonus. Oppidum est pulchrum.",
    "Domina et fīlia in vīllā sunt. Fīlia mātrem iuvat. Māter est laeta. Fīlia est bona. Vīlla est pulchra.",
    "Pater et servus in hortō sunt. Pater herbam secat. Servus aquam portat. Hortus est pulcher. Sunt bonī.",
    "Māter et puella in culīnā sunt. Māter cibum facit. Puella mātrem spectat. Cibus est bonus. Sunt laetae.",
    "Puerī et puellae in campō sunt. Puerī currunt. Puellae rīdent. Sōl lūcet. Diēs est bonus. Omnēs sunt laetī.",
    "Servī et dominae in vīllā sunt. Servī labōrant. Dominae sedent. Vīlla est pulchra. Omnēs sunt bonī.",
    "Dominī et puerī in oppidō sunt. Dominī ambulant. Puerī lūdunt. Oppidum est magnum. Omnēs sunt laetī.",
    "Sōl oritur. Caelum est rubrum. Avēs cantant. Puerī in viā sunt. Novus diēs est.",
    "Sōl cadit. Caelum est rubrum. Avēs tacent. Puerī in vīllīs sunt. Nox venit.",
    "Lūna oritur. Stēllae in caelō sunt. Caelum est nigrum. Nox est pulchra. Terra tacet.",
    "Māne est. Sōl in caelō est. Pater surgit. Māter surgit. Fīlius et fīlia surgunt. Familia est laeta.",
    "Vesperī est. Sōl in caelō nōn est. Familia in vīllā est. Pater cibum edit. Omnēs sunt laetī.",
    "Nocte, lūna in caelō est. Stēllae sunt clārae. Puerī dormiunt. Puellae dormiunt. Omnēs dormiunt.",
    "Hodiē diēs bonus est. Sōl lūcet. Avēs cantant. Herba est viridis. Puerī in hortō lūdunt.",
    "Herī diēs bonus erat. Sōl lūcēbat. Avēs cantābant. Puerī in hortō lūdēbant. Omnēs erant laetī.",
    "Crās diēs bonus erit. Sōl lūcēbit. Avēs cantābunt. Puerī in hortō lūdent. Omnēs erunt laetī.",
    "Puer 'Salvē' dīcit. Puella 'Salvē' dīcit. Puer et puella sunt amīcī. Amīcī sunt bonī. Sunt laetī.",
    "Pater 'Venī' dīcit. Fīlius venit. Pater 'Tū es bonus puer' dīcit. Fīlius est laetus. Pater fīlium amat.",
    "Māter 'Venī' dīcit. Fīlia venit. Māter 'Tū es bona puella' dīcit. Fīlia est laeta. Māter fīliam amat.",
    "Dominus 'Portā aquam' dīcit. Servus aquam portat. Dominus 'Bene' dīcit. Servus est laetus. Dominus est bonus.",
    "Domina 'Carpe rosam' dīcit. Puella rosam carpit. Domina 'Bene' dīcit. Puella est laeta. Domina est bona.",
    "Puer 'Ego aquam videō' dīcit. Aqua in fluviō est. Aqua est clāra. Puer aquam bibit. Puer est laetus.",
    "Puella 'Ego rosam videō' dīcit. Rosa in hortō est. Rosa est rubra. Puella rosam carpit. Puella est laeta.",
    "Servus 'Ego cibum faciō' dīcit. Cibus in mēnsā est. Cibus est bonus. Dominus cibum edit. Servus est laetus.",
    "Dominus 'Ego amīcōs videō' dīcit. Amīcī in oppidō sunt. Amīcī sunt bonī. Dominus est laetus. Diēs est bonus.",
    "Domina 'Ego librum videō' dīcit. Liber in mēnsā est. Liber est bonus. Domina librum videt. Domina est laeta.",
    "Pater 'Ego fīlium amō' dīcit. Fīlius est parvus. Fīlius est bonus. Pater fīlium tangit. Fīlius est laetus.",
    "Māter 'Ego fīliam amō' dīcit. Fīlia est parva. Fīlia est bona. Māter fīliam tangit. Fīlia est laeta.",
    "Puer 'Ego nōn timeō' dīcit. Nox est. Caelum est nigrum. Puer in lectō est. Puer dormit. Puer est bonus.",
    "Puella 'Ego nōn timeō' dīcit. Nox est. Stēllae in caelō sunt. Puella in lectō est. Puella dormit. Puella est bona.",
    "Servus 'Ego labōrō' dīcit. Servus in hortō est. Herba est viridis. Servus herbam secat. Servus est bonus.",
    "Dominus 'Ego ambulō' dīcit. Dominus in oppidō est. Oppidum est magnum. Dominus virōs salūtat. Dominus est laetus.",
    "Domina 'Ego cantō' dīcit. Domina in vīllā est. Vīlla est pulchra. Domina cantat. Vōx eius est pulchra.",
    "Pater 'Ego in hortō labōrō' dīcit. Hortus est pulcher. Pater herbam secat. Pater rosās aquam dat. Pater est bonus.",
    "Māter 'Ego cibum faciō' dīcit. Culīna est parva. Māter cibum in mēnsā pōnit. Cibus est bonus. Familia est laeta.",
    "Fīlius 'Ego in campō lūdō' dīcit. Campus est magnus. Fīlius cum amīcīs currit. Fīlius rīdet. Fīlius est laetus.",
    "Fīlia 'Ego in hortō sedeō' dīcit. Hortus est pulcher. Fīlia rosās spectat. Fīlia cantat. Fīlia est laeta.",
    "Puer et puella 'Nōs sumus amīcī' dīcunt. Puer puellam iuvat. Puella puerum iuvat. Sunt laetī. Amīcī sunt bonī.",
    "Pater et māter 'Nōs fīlium amāmus' dīcunt. Fīlius est bonus. Pater et māter sunt laetī. Familia est bona.",
    "Servī 'Nōs labōrāmus' dīcunt. Servī in vīllā sunt. Servī cibum faciunt. Servī aquam portant. Servī sunt bonī.",
    "Dominī 'Nōs ambulāmus' dīcunt. Dominī in oppidō sunt. Dominī virōs salūtant. Dominī rīdent. Dominī sunt laetī.",
    "Puer 'Aqua est frīgida' putat. Puer in fluviō natat. Aqua est clāra. Puer est laetus. Sōl lūcet.",
    "Puella 'Rosa est pulchra' putat. Puella in hortō est. Rosa est rubra. Puella rosam carpit. Puella est laeta.",
    "Servus 'Dominus est bonus' putat. Servus in vīllā labōrat. Dominus servum iuvat. Servus est laetus. Dominus est bonus.",
    "Dominus 'Servus est bonus' putat. Dominus in vīllā est. Servus labōrat. Dominus est laetus. Servus est bonus.",
    "Domina 'Vīlla est pulchra' putat. Domina in vīllā sedet. Vīlla est magna. Domina est laeta. Vīlla est pulchra.",
    "Pater 'Fīlius est bonus' putat. Pater in hortō est. Fīlius patrem iuvat. Pater est laetus. Fīlius est bonus.",
    "Māter 'Fīlia est bona' putat. Māter in vīllā est. Fīlia mātrem iuvat. Māter est laeta. Fīlia est bona.",
    "Puer 'Hic diēs est bonus' putat. Sōl lūcet. Avēs cantant. Puer in hortō lūdit. Puer est laetus. Diēs est bonus.",
    "Puella 'Haec rosa est pulchra' putat. Rosa in hortō est. Rosa est rubra. Puella rosam spectat. Puella est laeta.",
    "Servus 'Hoc oppidum est parvum' putat. Servus in oppidō est. Oppidum est parvum. Servus cibum emit. Servus est bonus.",
    "Dominus 'Haec via est longa' putat. Dominus in viā ambulat. Via est longa. Dominus ad oppidum it. Dominus est bonus.",
    "Domina 'Hic hortus est pulcher' putat. Domina in hortō sedet. Hortus est pulcher. Domina rosās spectat. Domina est laeta.",
    "Pater 'Hic liber est bonus' putat. Pater librum videt. Liber est in mēnsā. Pater librum amat. Liber est pulcher.",
    "Māter 'Hic cibus est bonus' putat. Māter cibum facit. Cibus in mēnsā est. Māter cibum edit. Cibus est bonus.",
    "Fīlius 'Hic canis est albus' putat. Fīlius canem videt. Canis in viā est. Fīlius canem amat. Canis est bonus.",
    "Fīlia 'Haec avis est parva' putat. Fīlia avem videt. Avis in hortō est. Fīlia avem audit. Avis cantat. Avis est pulchra.",
]

def replace_in_text(text, max_chapter):
    words = re.findall(r'[āēīōūȳĀĒĪŌŪȲa-zA-Z]+', text)
    high_chapter_words = set()
    for w in set(words):
        clean = re.sub(r'[āēīōūȳĀĒĪŌŪȲ]',
                       lambda m: 'aeiouyAEIOUY'['āēīōūȳĀĒĪŌŪȲ'.index(m.group(0))], w).lower()
        ch = FORM_CHAPTER.get(clean)
        if ch is not None and ch > max_chapter:
            high_chapter_words.add(w)

    result = text
    for w in sorted(high_chapter_words, key=len, reverse=True):
        replacement = REPLACEMENTS.get(w.lower())
        if replacement is None:
            clean = re.sub(r'[āēīōūȳĀĒĪŌŪȲ]',
                           lambda m: 'aeiouyAEIOUY'['āēīōūȳĀĒĪŌŪȲ'.index(m.group(0))], w)
            replacement = REPLACEMENTS.get(clean.lower())
        if replacement:
            if w[0].isupper() and w == w[0].upper() + w[1:].lower():
                replacement = replacement[0].upper() + replacement[1:]
            result = re.sub(r'\b' + re.escape(w) + r'\b', replacement, result)
    return result

def expand_text(text, target_words):
    current_words = len(text.split())
    if current_words >= target_words:
        return text
    needed = target_words - current_words
    expanded = text.rstrip()
    added = 0
    sent_idx = 0
    while added < needed:
        sent = SAFE_SENTENCES[sent_idx % len(SAFE_SENTENCES)]
        sent_words = len(sent.split())
        expanded += " " + sent
        added += sent_words
        sent_idx += 1
    return expanded

def fix_file(filepath, target_words, max_chapter):
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    
    parts = content.split('---\n', 2)
    if len(parts) < 3:
        print(f"  SKIP: no valid YAML frontmatter")
        return None
    
    yaml_header = parts[1]
    body = parts[2]
    
    # 替换高章节词汇
    fixed_body = replace_in_text(body, max_chapter)
    
    # 扩充
    expanded_body = expand_text(fixed_body, target_words)
    
    new_wc = len(expanded_body.split())
    
    new_content = '---\n' + yaml_header + '---\n' + expanded_body
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    return new_wc

if __name__ == "__main__":
    cap_dir = BASE / "realitates" / "Cap12"
    
    targets = {
        "medius": 600,
        "longior": 800,
        "longus": 1500,
    }
    
    for tier, target in targets.items():
        for f in sorted(cap_dir.glob(f"Cap12_*_{tier}_*.md")):
            new_wc = fix_file(str(f), target, 14)
            if new_wc:
                print(f"Fixed {f.name}: {new_wc} words")
    
    print("Done!")